name: pre-commit

on:
  pull_request:
    branches:
      - main

jobs:
  lint-pr-title:
    name: Validate PR titles
    runs-on: ubuntu-latest
    if: ${{ github.actor != 'pull[bot]' }}
    steps:
      - uses: amannn/action-semantic-pull-request@v5.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gabe565/setup-helm-docs-action@v1
      - uses: pre-commit/action@v3.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  chart-version-bumps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup updatecli
        uses: updatecli/updatecli-action@v2

      - name: Bump any charts that require it
        run: |
          make updatecli/internal
          git diff > bump.log
        env:
          UPDATECLI_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment PR with needed changes
        if: ${{ steps.bump-changes.outputs.diff != '' }}
        uses: thollander/actions-comment-pull-request@v2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          filePath: bump.log
          comment_tag: chart-bump-changes
          reactions: eyes

      - name: Fail if chart versions needed to be bumped
        run: |
          if [ -s bump.log ]; then
            echo "Chart version bumps are needed. Please check the PR comments."
            exit 1
          fi
